### PR TITLE
feat(notebook): applied design

### PR DESCRIPTION
**Pull request by neighborhood999**
## Screenshots

截圖 2021-11-22 下午12 08 20

截圖 2021-11-22 下午12 08 25

截圖 2021-11-22 下午12 08 13

Signed-off-by: Jie Peng <im@jiepeng.me>
Co-authored-by: Timothy Lee <ctiml@infuseai.io>

** PR checklist **

- [x] Ensure you have added or ran the appropriate tests for your PR.
- [x] DCO signed

### CODE REVIEW

**Comment by ggosiang** [comment]
can we move the buttons of "Access Server" and "Stop server" further right to align with the design?
- design
Screen Shot 2021-11-22 at 16 35 28
- current
Screen Shot 2021-11-22 at 16 35 40

**Comment by neighborhood999** [comment]
> can we move the buttons of "Access Server" and "Stop server" further right to align with the design?
> 
>     * design
>       Screen Shot 2021-11-22 at 16 35 28
> 
>     * current
>       Screen Shot 2021-11-22 at 16 35 40

Like this?
截圖 2021-11-22 下午4 52 41

**Comment by neighborhood999** [comment]
> > > can we move the buttons of "Access Server" and "Stop server" further right to align with the design?
> > > ```
> > > * design
> > >   Screen Shot 2021-11-22 at 16 35 28
> > > 
> > > * current
> > >   Screen Shot 2021-11-22 at 16 35 40
> > > ```
> > 
> > 
> > Like this? 截圖 2021-11-22 下午4 52 41
> 
> yes!
> 
> based on figma, can we hide the "Remove From Instance" button if the notebook instance is running? (green box indicated)
> 
> also, there is a small offset between "Stop server" button and the far right of the table. can we adjust it to align with "Remove From Instance" button? if it is limited by design, skipping this one would be fine. (gray box indicated) Screen Shot 2021-11-22 at 17 14 45

Updated.

**Review by ggosiang — APPROVED** [review]
LGTM

**Pull request merged**
