### PR TITLE
chart documentation

### LINKED ISSUE #8: docs about basic usage
how to configure local users or federation in keycloak, and link to keycloak guides

### PR DESCRIPTION
**Pull request by popcornylu**
Closes #8 
Clubehouse: [ch353](https://app.clubhouse.io/infuseai/story/353/primehub-ce-chart-documentation)

Please see [document in branch](https://github.com/InfuseAI/primehub/tree/feature/ch353/primehub-ce-chart-documentation) to review

Important note:
1. Add `docs/getting_started.md` and `docs/install.md` document
2. Move most of DEV environment setup instructions to getting started doc.
3. Remove cookie secret setting in default `values.yaml`. Because we assume there is persistence storage by default. 
https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#hub-cookiesecret
4. Move helm/config-kind.yaml → examples/config-kind.yaml, 
5. Move helm/config-persist.yaml → examples/config-persist.yaml

### CODE REVIEW

**Comment by clkao** [comment]
Please try to refer to the examples/config-* file in the docs, otherwise things maybe out of sync.

**Comment by jackklpan** [comment]
https://www.notion.so/infuseai/CE-README-QUESTIONS-79031ec4aa724f6585b486ad4a294d24

**Comment by popcornylu** [comment]
in gke setup, there is no persistence volume in the home folder.

**Comment by popcornylu** [comment]
in the installation guideline, should add ingress install snippet and specify `ingress-ngnix` as installed namespace.

**Comment by popcornylu** [comment]
In installation guideline, recommend to use `xip.io` domain name as primehub service domain name.

**Comment by popcornylu** [comment]
> Please try to refer to the examples/config-* file in the docs, otherwise things maybe out of sync.

Done.

**Comment by popcornylu** [comment]
> in gke setup, there is no persistence volume in the home folder.
> in the installation guideline, should add ingress install snippet and specify nginx-ingress as installed namespace.
> in the installation guideline, should add ingress install snippet and specify nginx-ingress as installed namespace.

Fixed.

**Pull request merged**
